# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57052ce191edfabc362586713866c4606f8ce6baf21519b838366589612b217e7e890a2cef14171be02d978dc27233454965ec1eb49fd7c1acf23fd61b58a11c

test:
  secret_key_base: a8ceb1993a4ba290ea8956e85829f651d4f4c777409aa56d88b47e79555c09fbcf2081697c3bd0df5b6c232372332f6db014d7e5ecbf58939da88e38866dd753

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
